// Canonical development schema. Used by the explicit bootstrap script
// and by read-only assertSchema(). Must not be executed on app startup.

export const EXPECTED_TABLES = [
  'products',
  'customers',
  'refurb_items',
  'sales',
  'refurb_details',
  'ebay_updates',
  'export_logs',
  'trade_ins',
  'backup_files',
];

export const EXPECTED_COLUMNS = {
  products: [
    'id',
    'sku',
    'code',
    'name',
    'notes',
    'on_ebay',
    'cost',
    'retail',
    'fees',
    'postage',
    'postage_group',
    'quantity',
    'ebay_status',
    'ebay_notes',
    'needs_pics',
    'battery_health',
    'server_cpu_1',
    'server_cpu_2',
    'server_ram',
    'server_hdd',
    'created_at',
  ],
  customers: [
    'id',
    'name',
    'phone',
    'email',
    'id_image_path',
    'notes',
    'address',
    'created_at',
    'updated_at',
  ],
  refurb_items: [
    'id',
    'sku',
    'serial',
    'description',
    'status',
    'parts_status',
    'supplier',
    'cost',
    'retail',
    'notes',
    'created_at',
    'cpu',
    'category',
    'colour',
    'storage',
    'controller',
    'quantity',
  ],
  sales: [
    'id',
    'product_id',
    'sku',
    'quantity',
    'unit_cost',
    'unit_retail',
    'fees',
    'postage',
    'channel',
    'order_ref',
    'note',
    'created_at',
  ],
  refurb_details: [
    'refurb_id',
    'specs_cpu',
    'specs_ram',
    'specs_storage',
    'specs_gpu',
    'specs_screen',
    'os_version',
    'parts_needed',
    'parts_cost',
    'checklist',
    'notes',
    'updated_at',
    'specs_colour',
    'specs_network',
    'specs_condition',
    'specs_firmware',
    'specs_region',
    'specs_bundle',
  ],
  ebay_updates: [
    'id',
    'sku',
    'code',
    'delta',
    'old_qty',
    'new_qty',
    'note',
    'done',
    'created_at',
  ],
  export_logs: ['key', 'last_exported'],
  trade_ins: [
    'id',
    'customer_name',
    'customer_phone',
    'customer_email',
    'customer_address',
    'serial',
    'device_desc',
    'valuation',
    'agreed_value',
    'id_image_path',
    'refurb_id',
    'customer_id',
    'created_at',
  ],
  backup_files: ['id', 'filename', 'file_data', 'created_at'],
};

// FK-safe order: parents before children.
export const CREATE_STATEMENTS = [
  `CREATE TABLE products (
      id SERIAL PRIMARY KEY,
      sku TEXT UNIQUE NOT NULL,
      code TEXT,
      name TEXT NOT NULL,
      notes TEXT,
      on_ebay INTEGER NOT NULL DEFAULT 0,
      cost NUMERIC DEFAULT 0,
      retail NUMERIC DEFAULT 0,
      fees NUMERIC DEFAULT 0,
      postage NUMERIC DEFAULT 0,
      postage_group TEXT,
      quantity INTEGER DEFAULT 0,
      ebay_status TEXT NOT NULL DEFAULT 'not_listed',
      ebay_notes TEXT,
      needs_pics TEXT DEFAULT 'Y',
      battery_health TEXT,
      server_cpu_1 TEXT,
      server_cpu_2 TEXT,
      server_ram TEXT,
      server_hdd TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )`,
  `CREATE UNIQUE INDEX products_code_uq ON products(code) WHERE code IS NOT NULL`,
  `CREATE TABLE customers (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL,
      phone TEXT,
      email TEXT,
      id_image_path TEXT,
      notes TEXT,
      address TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    )`,
  `CREATE INDEX customers_name_idx ON customers (name)`,
  `CREATE INDEX customers_phone_idx ON customers (phone)`,
  `CREATE INDEX customers_email_idx ON customers (email)`,
  `CREATE TABLE refurb_items (
      id SERIAL PRIMARY KEY,
      sku TEXT,
      serial TEXT,
      description TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'refurb',
      parts_status TEXT NOT NULL DEFAULT 'none',
      supplier TEXT,
      cost NUMERIC DEFAULT 0,
      retail NUMERIC DEFAULT 0,
      notes TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      cpu TEXT,
      category TEXT,
      colour TEXT,
      storage TEXT,
      controller TEXT,
      quantity INTEGER NOT NULL DEFAULT 1
    )`,
  `CREATE TABLE sales (
      id SERIAL PRIMARY KEY,
      product_id INTEGER REFERENCES products(id),
      sku TEXT NOT NULL,
      quantity INTEGER NOT NULL,
      unit_cost NUMERIC,
      unit_retail NUMERIC,
      fees NUMERIC DEFAULT 0,
      postage NUMERIC DEFAULT 0,
      channel TEXT,
      order_ref TEXT,
      note TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )`,
  `CREATE TABLE refurb_details (
      refurb_id INTEGER PRIMARY KEY REFERENCES refurb_items(id) ON DELETE CASCADE,
      specs_cpu TEXT,
      specs_ram TEXT,
      specs_storage TEXT,
      specs_gpu TEXT,
      specs_screen TEXT,
      os_version TEXT,
      parts_needed TEXT,
      parts_cost NUMERIC(10,2) DEFAULT 0,
      checklist JSONB NOT NULL DEFAULT '{}'::jsonb,
      notes TEXT,
      updated_at TIMESTAMPTZ DEFAULT NOW(),
      specs_colour TEXT,
      specs_network TEXT,
      specs_condition TEXT,
      specs_firmware TEXT,
      specs_region TEXT,
      specs_bundle TEXT
    )`,
  `CREATE INDEX refurb_details_updated_idx ON refurb_details(updated_at)`,
  `CREATE TABLE ebay_updates (
      id SERIAL PRIMARY KEY,
      sku TEXT NOT NULL,
      code TEXT,
      delta INTEGER NOT NULL,
      old_qty INTEGER NOT NULL,
      new_qty INTEGER NOT NULL,
      note TEXT,
      done BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )`,
  `CREATE TABLE export_logs (
      key TEXT PRIMARY KEY,
      last_exported TIMESTAMPTZ NOT NULL
    )`,
  `CREATE TABLE trade_ins (
      id SERIAL PRIMARY KEY,
      customer_name TEXT NOT NULL,
      customer_phone TEXT,
      customer_email TEXT,
      customer_address TEXT,
      serial TEXT,
      device_desc TEXT NOT NULL,
      valuation NUMERIC(10,2),
      agreed_value NUMERIC(10,2),
      id_image_path TEXT,
      refurb_id INTEGER,
      customer_id INTEGER REFERENCES customers(id),
      created_at TIMESTAMPTZ DEFAULT NOW()
    )`,
  `CREATE TABLE backup_files (
      id SERIAL PRIMARY KEY,
      filename TEXT NOT NULL,
      file_data BYTEA NOT NULL,
      created_at TIMESTAMP DEFAULT NOW()
    )`,
];
